source 'http://rubygems.org'
gem 'redgreengrid', '~> 0.3.2'
gem 'html5-boilerplate', '~> 0.2.6'
gem 'sinatra', '~> 1.2.0.a'
gem 'middleman', :path => '~/Projekte/middleman'
gem 'rdiscount', '1.6.5'
gem 'maruku', '0.6.0'
gem 'jammit', '0.5.4'
gem 'minisyntax', :path => '~/Projekte/minisyntax'
