---
title: Barcamps und Spam?
description: I’m sad. Barcamp Riga sent spam to me. How could this happen?
---


Barcamps und Spam?
=================

Barcamps sind eine gute Sache. Viele Leute machen sich eine Menge Mühe, damit sie zum Erfolg werden. Einige Firmen leisten ihren Teil dazu. Am Ende kommt eine für alle Teilnehmer erfreulich kostenlose Veranstaltung raus.

So war ich auch sehr vom [Barcamp](http://barcamp.lv/) in [Riga](http://de.wikipedia.org/wiki/Riga) begeistert. Sehr gute Veranstaltungsräume – aber vor allem interessante Kontakte in einen für uns Deutsche eher unbekannten Teil des Web: Osteuropa bis [Zentralasien](http://de.wikipedia.org/wiki/Zentralasien).

Während hierzulande die [kommerzielle Nutzung des Barcamps](http://www.franztoo.de/?p=802) diskutiert wird, sind die Letten schon einen Schritt weiter. Ich staunte nicht schlecht, als ich beim Durchsuchen meines Spam-Ordners diese E-Mail fand:

<%= article_img 'barcamp-riga-spam.png', 'Ich benutze für jede Anmeldung eine nachvollziehbare E-Mail-Adresse (domainname@meinedomain).' %>

Schade, wenn eine Veranstaltung so endet.

Ich kenne viel Organisatoren deutscher Barcamps sowie Start-Ups. Keinem würde ich das zutrauen und bin bis jetzt auch nicht enttäuscht worden. Ich hoffe, dass es sich hierbei um ein „technisches Missgeschick“ handelt.
